server:
  port: 8080

spring:
  application:
    name: factorIT

# # # # # Base de datos # # # # #
  datasource:
    # Si usas Neon.tech u otro free tier, reemplaza esta URL por la que te provean
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/carrito_db}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:admin}
    url: jdbc:postgresql://localhost:5432/carrito_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

# # # # # Configuración ORM # # # # #
    jpa:
      hibernate:
        # 'update' creará/actualizará las tablas automáticamente basado en tus Entities
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuración de Swagger / OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method